apiVersion: apps/v1
kind: Deployment
metadata:
  name: nr-permitting-api
  labels:
    app: nr-permitting-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nr-permitting-api
  template:
    metadata:
      labels:
        app: nr-permitting-api
    spec:
      containers:
      - name: nr-permitting-api
        image: your-acr.azurecr.io/nr-permitting-api:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: host
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: password
        - name: KEY_VAULT_URL
          value: "https://your-keyvault.vault.azure.net/"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /liveness
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: nr-permitting-api-service
spec:
  selector:
    app: nr-permitting-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nr-permitting-api-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - api.nr-permitting.gov
    secretName: tls-secret
  rules:
  - host: api.nr-permitting.gov
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nr-permitting-api-service
            port:
              number: 80
